llm:
  groq:
    provider: "groq"
    model_name: "llama-3.3-70b-versatile"
    temperature: 0
    max_tokens: 2048

  cohere:
    provider: "cohere"
    model_name: "embed-english-light-v3.0"
    temperature: 0
    max_tokens: 2048

  # openai:
  #    provider: "openai"
  #    model_name: "gpt-4o"
  #    temperature: 0